### ISSUE TITLE
confused about load/loadcss/loadjs/importhtml functions

### ISSUE THREAD

**Issue by rmiaas** [JuliaGizmos/Blink.jl#122]
Hi,

Firstly, thank you for creating this package to integrate Electron with Julia. I am planning to use this for migrating GUI applications from MATLAB to JULIA and this package is exactly what i need.
I am having problems setting up and using it, though. The issue is with any of the functions load/loadcss/loadjs/importhtml. They do not seem to work, or I might be doing something wrong.
For example:
`loadcss!(w, "styles.css")`
does not apply any of the styles in the styles files in the directory.

`importhtml!(w, 'index.html')`
does not display the html page stored in the local directory. The app shows a blank screen.

I could not find answers about this anywhere, hence posting this here.

**Comment by marcel-goldschen-ohm** [comment]
Running into similar issue with Julia 1.0.3 and Blink 0.10.1 on MacOSX 10.14.1 unless I just don't understand the load function. For example, after creating a window w = ..., calling load!(w, "index.html") just hangs with a blank window. I can get around it by calling body!(w, read("body.html", String), async=false) which works fine. Am I not understanding the load function correctly? Btw, load!(w, "my.css") seems to work fine for me, as does loadurl(w, ...).

**Comment by rmiaas** [comment]
@marcel-goldschen-ohm I did find a workaround to this issue, but forgot to post it here. i feel the ``load!`` function does not work for html files. A workaround is to use the ``loadfile`` function from ``Blink.jl/src/AtomShell/window.jl``. However, the implementation only works for absolute paths (see [here](https://github.com/JunoLab/Blink.jl/blob/93edf72cbc7aecc1c9cf310f2420f6aa64d8b211/src/AtomShell/window.jl#L161)). As an example, this will work:
``runblink.jl``
```julia
using Blink

w = Window(;async=false)

loadfile(w, "D:\\blink\\index.html")
```

``index.html ``
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello Blink</title>
  </head>
  <body>
    <div>
      Testing for Blink.jl
    </div>
  </body>
  <script type="text/javascript">
    (function() {
      alert('JavaScript loaded');
    })();
  </script>
</html>
```
```julia
julia> include("runblink.jl")
```

**Comment by marcel-goldschen-ohm** [comment]
Thanks for the tip! Seems like a simple fix would be to have the load!() function call loadfile() when given a .html file path. Cheers.

**Comment by travigd** [comment]
These functions are for the most part not super well named, but generally `load!` should be renamed `import!`. We should try to clean this up.
