### ISSUE TITLE
Blink opens new window on IJulia

### ISSUE THREAD

**Issue by orhanabar** [JuliaGizmos/Blink.jl#175]
I am using IJulia to run julia codes.
When I run these 2 lines on Jupyter notebook:
```
using Blink
w = Window()
```
It opens a new window.
Is there any way to show this window as Jupyter output?

**Comment by travigd** [comment]
This is not possible. The goal of this package is to provide bindings to Electron for Julia, which requires running in an Electron window. To enable interactive output in IJulia/Jupyter, check out [WebIO.jl](https://github.com/JuliaGizmos/WebIO.jl).
