### ISSUE TITLE
Error "Unsatisfiable requirements detected for package Blink" in installation

### ISSUE THREAD

**Issue by tezzytezzy** [JuliaGizmos/Blink.jl#188]
I am not sure how to fathom the following error. Can anyone give me a pointer how to fix this? 
![blink error installation](https://user-images.githubusercontent.com/46082158/52913149-093f5580-32f6-11e9-95f3-c8aa94209092.png)

Packages installed:
![status](https://user-images.githubusercontent.com/46082158/52913154-18260800-32f6-11e9-9258-380431158996.png)

Version info:
![version](https://user-images.githubusercontent.com/46082158/52913160-2411ca00-32f6-11e9-9aa2-d0c264a040a5.png)

**Comment by travigd** [comment]
Is this still an issue?

**Comment by tezzytezzy** [comment]
Hi Travis,

Unfortunately the situation is slightly different, but the core problem seems to remain.

![versioninfo0](https://user-images.githubusercontent.com/46082158/62158390-1fe5d180-b2c4-11e9-8762-6b3343aa7adc.png)

![versioninfo](https://user-images.githubusercontent.com/46082158/62158394-23795880-b2c4-11e9-91d4-80ef6795fa20.png)

![add Blink](https://user-images.githubusercontent.com/46082158/62158401-27a57600-b2c4-11e9-9b35-3d02a9cd19fc.png)

**Comment by travigd** [comment]
Looks like this is because Atom is restricted to a certain version? I'm also not sure what this has to do with Blink because we don't depend on either Atom or ASTInterpreter2.

**Comment by rdeits** [comment]
Might just need a `Pkg.update()` (ref: https://discourse.julialang.org/t/error-unsatisfiable-requirements-detected-for-package-astinterpreter2-e6d88f4b/22224 and https://discourse.julialang.org/t/error-unsatisfiable-requirements-detected-for-package-astinterpreter2-e6d88f4b/22225 )

**Comment by tezzytezzy** [comment]
@rdeits: You nailed it, mate!

![no error](https://user-images.githubusercontent.com/46082158/62318572-fe662080-b450-11e9-94dd-6a5429cd6641.png)

Thank you very much!
