### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by travigd** [JuliaGizmos/Blink.jl#191]
I get this error while running the test suite for WebIO.

![Screenshot from 2019-03-13 18-45-49](https://user-images.githubusercontent.com/773453/54319561-4975b900-45c0-11e9-839c-d48f7c7bc4ac.png)

I tried uninstalling and then reintalling AtomShell but no juice. This is new because I was able to run the test suite previously (this is on `WebIO@0.7.0` FYI - the "legacy" WebIO).

**Comment by travigd** [comment]
Infuriatingly enough, this only occurs when running in an `@testset`?

```julia
using Blink, Test
@testset "testset" begin
    println("Opening Window...")
    w = Window(Dict(:show => true))
    Blink.opentools(w)
    println("Open!")
end
```

The output is
```
Opening Window...
```
followed by the error message above popup above. When I close the popup, things proceed but setting the body doesn't work (I think).

Commenting out the `@testset` and accompanying `end` works without a hitch.

**Comment by travigd** [comment]
Ubuntu 18.04
```
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
julia> Pkg.status()
    Status `~/.julia/environments/v1.0/Project.toml`
  [bf4720bc] AssetRegistry v0.1.0
  [c52e3926] Atom v0.7.15
  [ad839575] Blink v0.10.1
  [7073ff75] IJulia v1.17.0
  [c601a237] Interact v0.9.1
  [97c1335a] JSExpr v0.5.0
  [682c06a0] JSON v0.20.0
  [e5e0dc1b] Juno v0.5.5
  [0db19996] NBInclude v2.1.0
  [2bd173c7] NodeJS v0.6.0
  [510215fc] Observables v0.2.3
  [9b87118b] PackageCompiler v0.6.3
  [f0f68f2c] PlotlyJS v0.12.3+ [`~/.julia/dev/PlotlyJS`]
  [91a5bcdd] Plots v0.23.1
  [d330b81b] PyPlot v2.8.0
  [112f6efa] VegaLite v0.6.0
  [0f1e0344] WebIO v0.7.0+ [`~/.julia/dev/WebIO`]
  [8ba89e20] Distributed 
```

**Comment by travigd** [comment]
This is what it's barfing about.
```
{"type":"eval","code":"withwin(1,\"this.openDevTools()\")","callback":2}{"type":"eval","code":"createWindow({\"node-integration\":false,\"url\":\"http://127.0.0.1:2470/1\",\"show\":true,\"icon\":\"/home/travigd/.julia/packages/Blink/1QOOi/deps/julia.png\",\"title\":\"Julia\",\"use-content-size\":true})","callback":1}GET /1 HTTP/1.1^M
```

Note the extraneous `GET /1 HTTP/1.1^M` at the end.

**Comment by travigd** [comment]
This even occurs when running
```julia
Pkg.test("Blink")
```
for me.

**Comment by NHDaly** [comment]
Thanks for finding that @travigd! :)

**Comment by NHDaly** [comment]
Is this closed by https://github.com/JunoLab/Blink.jl/pull/193?

**Comment by travigd** [comment]
I would consider #193 to be a solution for the symptoms rather than curing the root issue. Questions remaining are...
* Why does this only happen in a `@testset`?
* Why does debugging info from what appears to be HTTP.jl go into the electron server?

**Comment by travigd** [comment]
This doesn't seem(?) to be an issue anymore (#231).
