### ISSUE TITLE
Blink window disappeared soon after it was opened ?

### ISSUE THREAD

**Issue by kailotus** [JuliaGizmos/Blink.jl#195]
Hello Everyone :
I used Blink to make Julia's GUI application. There is a code (BlinkApp.jl) as follows:
~~~~~
using Blink
w = Window()
body!(w, "Hello Blink")
~~~~~
When I use Julia REPL to execute:
Julia> include("BlinkApp.jl")
The Blink window can be displayed normally.

But when I use the MS Windows command prompt and give the command:
C:\Temp>julia BlinkApp.jl
I found that the window flickered and disappeared. 
Has anyone ever had such a situation?
By the way, please ask how to solve this problem?
Thank you all.

**Comment by srgk26** [comment]
@kailotus I have the same problem too. Running Blink script from the command line doesn't work, though works from Julia REPL.

**Comment by pfitzseb** [comment]
You have to make sure that Julia stays alive after your script has run, e.g. by having your last statement be `readline()` or something like that.

**Comment by srgk26** [comment]
> You have to make sure that Julia stays alive after your script has run, e.g. by having your last statement be `readline()` or something like that.

@pfitzseb Thank you, it works. But the problem is it also causes the terminal to be hung, cos the computer is waiting for a return value from `readline()`, which it never gets. I am trying to build an app that uses Blink, and using this method causes the app to crash, even though the terminal executable works fine. But that's only because terminal itself is hung.

I will try to work around that. But could there be a neater way to do this?

**Comment by pfitzseb** [comment]
I mean you could also try to spawn another Julia process that stays alive even if the explicitly started one dies, but this is fairly standard behaviour.

**Comment by travigd** [comment]
We should probably add a `waitclosed`-type function that blocks until the Window is closed (so that cleanup tasks can be performed). This would allow you to just include `waitclosed(w)` at the end of a Julia file to keep things open.

**Comment by mlhetland** [comment]
Is there an issue that relates to this `waitclosed`-type function, or has something like it been added? (If not, I guess you could reopen this issue as a placeholder?) Currently, the best solution I've found (cf. [this Discourse post](https://discourse.julialang.org/t/sync-keepalive-for-blink-jl-interact-jl)) for using `Blink.jl` in a script (and not the REPL) is:

```julia
while active(w)
    sleep(1)
end
```

Is there a more idiomatic way of doing this, at present?

**Comment by sina-masoud-ansari** [comment]
I had a similar issue with getting Interact.jl to work with Mux.jl from a script. One way to resolve the issue is to add the following to the end of the script:

```Base.JLOptions().isinteractive==0 && wait()```

Source: https://github.com/JuliaWeb/Mux.jl/issues/73

`waitclosed` would be preferred though to allow cleanup as mentioned already.

**Comment by travigd** [comment]
#254
