### ISSUE TITLE
I'm trying to use Jquery

### ISSUE THREAD

**Issue by Chiyoku** [JuliaGizmos/Blink.jl#196]
I'm trying to load Jquery with loadJS! but when i use @js says that $ not exists...
lero() is a function that calls $("button") only.
```
using Blink

w = Window(Dict("autoHideMenuBar"=>true))

load!(w,"ui/jquery.js");
body!(w,String(read("ui/index.html")));
tools(w)

while true
    @js w lero()
    sleep(1)
 end
 
```

**Comment by Chiyoku** [comment]
ERROR: LoadError: Javascript error      ReferenceError: $ is not defined
```
<script>
    var turn = false;
    function lero() {
        if(turn){
            $("#a").text("changed")
        }else{
            $("#a").text("nto changed")
        }
        turn = !turn;
    }
</script>
``` 
trying to execute this code
but it didnt happen when its only

```
<script>
    var turn = false;
    
    function lero() {
         $("#a").text("changed")
    }
</script>
```

**Comment by pfitzseb** [comment]
Hm, try loading jquery in your `index.html`. Not sure how consecutive calls to `load!` and `body!` interact

**Comment by travigd** [comment]
`load!` is poorly named - it just calls `importhtml!` and friends, it doesn't actually set the content of the window. Is `ui/jquery.js` a file available on your machine?

Try
```
load!(w, "https://code.jquery.com/jquery-3.4.1.min.js")
```
instead.
