### ISSUE TITLE
Import Javascript variables into Julia 

### ISSUE THREAD

**Issue by srgk26** [JuliaGizmos/Blink.jl#197]
I am developing a GUI where I would get user input and use the input value to do something else within Julia. I found a way to do this with another method, but I'm now trying to use HTML/CSS as the main styling code and would need to communicate between javascript and julia. I could not find a solution for this from anywhere. #29 mentions little about it, but I can't get to work around this still.

This is a very simple code for a Blink window:

```
using Blink
w = Blink.Window()
Blink.body!(w, html"""<input id="test" placeholder="Enter text here"><button onclick='Blink.msg("press", "foo")'>Press me!</button>""")
Blink.handle(w, "press") do args...
    Blink.body!(w, @js_ w document.getElementById("test").value)
end
```

The page layout works (it shows the input text field and the click button). But when I click the button, it doesn't show the value of the text input. I know that the message passing works though since this works:

```
Blink.handle(w, "press") do args...
    Blink.body!(w, "This works!")
end
```

I also know that the javascript function `document.getElementById("test").value` works because this works:

```
Blink.handle(w, "press") do args...
    @js_ w alert(document.getElementById("test").value)
end
```

The problem therefore is accessing the input text value from within julia. I need to access this input text value from within Julia. I would appreciate if anyone could help.

**Comment by pfitzseb** [comment]
I'd recommend using WebIO.jl for this.

**Comment by srgk26** [comment]
> I'd recommend using WebIO.jl for this.

Thank you, I'll check it out.
