### ISSUE TITLE
README.md Blink.AtomShell.window() Error: syntax: invalid identifier name "..."

### ISSUE THREAD

**Issue by comaldave** [JuliaGizmos/Blink.jl#203]
### New user here, following the README, I copy and paste the lines.
```
julia> Blink.AtomShell.Window(...)
ERROR: syntax: invalid identifier name "..."
```
### The workaround seems to be:
```
julia> Blink.AtomShell.Window()
Window(2, Electron(Process(`/home/david/.juliapro/JuliaPro_v1.1.1.1/packages/Blink/1QOOi/deps/atom/electron /home/david/.juliapro/JuliaPro_v1.1.1.1/packages/Blink/1QOOi/src/AtomShell/main.js port 3622`, ProcessRunning), Sockets.TCPSocket(RawFD(0x00000021) active, 0 bytes waiting), Dict{String,Any}("callback"=>##1#2())), Page(2, #undef, Dict{String,Any}("callback"=>##1#2()), Distributed.Future(1, 1, 2, nothing)))
```
I know that script kiddies should not copy and paste lines found on the Internet without understanding them but a new user should not have to debug the install directions.

### Using;
    Operating System: Fedora 30
    KDE Plasma Version: 5.15.5
    KDE Frameworks Version: 5.58.0
    Qt Version: 5.12.1
    Kernel Version: 5.1.6-300.fc30.x86_64
    OS Type: 64-bit
    Processors: 6 × AMD Phenom(tm) II X6 1055T Processor
    Memory: 7.8 GiB of RAM

**Comment by travigd** [comment]
The code in the README is an example of what happens at the REPL.

```julia
julia> w = Window() # Open a new window
Blink.AtomShell.Window(...)
```

The output isn't mean to be run (the `w = Window()` part is). The `...` makes a lot of sense because it's very ugly otherwise (we could make pretty-printing better):
```
julia> w = Window()
Window(1, Electron(Process(`/Users/travisd/.julia/dev/Blink/deps/Julia.app/Contents/MacOS/Julia /Users/travisd/.julia/dev/Blink/src/AtomShell/main.js port 6290`, ProcessRunning), Sockets.TCPSocket(RawFD(0x00000012) active, 0 bytes waiting), Dict{String,Any}("callback"=>##1#2())), Page(1, WebSocket(server, CONNECTED), Dict{String,Any}("webio"=>##28#29{WebIOBlinkComm}(WebIOBlinkComm(Window(#= circular reference @-5 =#))),"callback"=>##1#2()), Distributed.Future(1, 1, 1, Some(true))), Task (done) @0x0000000115850010)
```
