### ISSUE TITLE
A simple Example 

### ISSUE THREAD

**Issue by alirezamecheng** [JuliaGizmos/Blink.jl#204]
Hello,
I read the documentation and I am confused about the Julia and JavaScript communication (Maby because I have no experience in web development). 

I need a simple GUI for my app in a way that the user has three number input forms which by inputting two of them the third one will be calculated by the Julia program and a selection box that returns the selected value to the Julia program then there is a calculate button that runs a function with inputted numbers and selected value from the form. 

It will be appreciated if you can help me and give me some examples.

**Comment by travigd** [comment]
Check this out: https://gist.github.com/travigd/f0ac838addf5f4db06d56da9360275fe

**Comment by CuriosityChannel** [comment]
> Check this out: https://gist.github.com/travigd/f0ac838addf5f4db06d56da9360275fe

Thanks, It may be a good starting point for me. 
Please send me any Example you may find. It will be a very good help.

**Comment by alirezamecheng** [comment]
>    Check this out: https://gist.github.com/travigd/f0ac838addf5f4db06d56da9360275fe

Thanks, It may be a good starting point for me.
Please send me any Example you may find. It will be a very good help.

**Comment by alirezamecheng** [comment]
I also found this. I leave it here for others.
https://github.com/JuliaGizmos/Interact.jl/issues/36

**Comment by NHDaly** [comment]
@alirezamecheng this section of the documentation (accessible from the README) contains a simple example of javascript <-> julia communication:
https://juliagizmos.github.io/Blink.jl/latest/guide/#.-Setting-up-interaction-between-Julia-and-JS-1

And it links to this larger page which entirely covers that topic:
https://juliagizmos.github.io/Blink.jl/latest/communication/

The documentation is definitely very sparse, so feel free to send a PR to update it if you have any recommendations! :) We always love documentation PRs! :)
