### ISSUE TITLE
Checking wether a window is open or not

### ISSUE THREAD

**Issue by alirezamecheng** [JuliaGizmos/Blink.jl#210]
It would be nice to have a function or sth else to check if the `Window` is open or not?
I couldn't find that if it is available already.

**Comment by NHDaly** [comment]
https://github.com/JuliaGizmos/Blink.jl/pull/212 :)

Sorry it wasn't documented. Many Blink functions still do not have documentation. If you come across other functions like this, please open a PR to add documentation! :)

**Comment by alirezamecheng** [comment]
Thanks. I will be happy if I can help and contribute.

**Comment by alirezamecheng** [comment]
Just for others that may see this post. 
To check wether a windows is open or not you can use the `Blink.active(w::Window)` command as example below:
```julia 
julia> using Blink

julia> w = Window(); # this command will open a window and name it `w`
julia> active(w) # will check if the window is open 
true
julia> active(w) # returns `false` if you close the window
false
```
