### ISSUE TITLE
Loading a local JS script with loadjs!

### ISSUE THREAD

**Issue by chakravala** [JuliaGizmos/Blink.jl#219]
Hi, I'd like to run following `loadjs!` command on a local file
```Julia
loadjs!(Window(), "https://unpkg.com/ganja.js")
```
However, I would like to save `ganja.js` locally, so if I try
```Julia
loadjs!(Window(), "file://directory/ganja.js")
```
It doesn't work, so how can I load it locally?

**Comment by travigd** [comment]
Typically, in Node, imports are relative. Try using WebIO for this.

https://juliagizmos.github.io/WebIO.jl/latest/api/asset/

```julia
ganja = Asset("/path/to/ganja.js")
js(Window(), js"""
$(ganja).then((ganja) => {
  // use ganja
});
"""

# Using async/await
(async function() {
  const ganja = await $ganja;
  // use ganja
})();
"""
```

Reopen if you have issues. :^)
