### ISSUE TITLE
Blink looking for 7z.exe in wrong place (Julia 1.3.0)

### ISSUE THREAD

**Issue by pgunnink** [JuliaGizmos/Blink.jl#224]
Blink currently looks for 7z.exe on Windows in the location `joinpath(ENV["LOCALAPPDATA"], juliafolders[i], "bin", "7z.exe")`, (see install.jl [here](https://github.com/JuliaGizmos/Blink.jl/blob/93edf72cbc7aecc1c9cf310f2420f6aa64d8b211/src/AtomShell/install.jl#L67)) which is no longer supported in Julia 1.3.0. `7z.exe` now lives in `joinpath(Sys.BINDIR, "..", "libexec")`, as indicated in this [Julia PR](https://github.com/JuliaLang/julia/pull/33493) and also verified on a new install of Julia 1.3.0 on my Windows machine. 

This should be relatively trivial to fix by checking for the version number and selecting the right folder, or simply by trying both folders. I would be willing to make a PR for this, but I don't know which approach would be preferable.

**Comment by pgunnink** [comment]
I created a [PR here](https://github.com/JuliaGizmos/Blink.jl/pull/225).

**Comment by travigd** [comment]
Closed by #229.
