### ISSUE TITLE
Build error on Windows with Julia 1.0.5

### ISSUE THREAD

**Issue by tkoolen** [JuliaGizmos/Blink.jl#226]
We're seeing a build error on Travis with Julia 1.0 only, 1.1 and 1.2 are fine. Error here: https://ci.appveyor.com/project/rdeits/meshcat-jl/builds/29751069/job/alb7jscpn4fxnimd#L169

```julia
┌ Error: Error building `Blink`: 
│ ERROR: LoadError: ArgumentError: reducing over an empty collection is not allowed
│ Stacktrace:
│  [1] _empty_reduce_error() at .\reduce.jl:212
│  [2] reduce_empty(::Function, ::Type) at .\reduce.jl:222
│  [3] mapreduce_empty(::typeof(identity), ::Function, ::Type) at .\reduce.jl:247
│  [4] _mapreduce(::typeof(identity), ::typeof(max), ::IndexLinear, ::Array{VersionNumber,1}) at .\reduce.jl:301
│  [5] _mapreduce_dim at .\reducedim.jl:312 [inlined]
│  [6] #mapreduce#584 at .\reducedim.jl:307 [inlined]
│  [7] mapreduce at .\reducedim.jl:307 [inlined]
│  [8] _maximum at .\reducedim.jl:657 [inlined]
│  [9] _maximum at .\reducedim.jl:656 [inlined]
│  [10] #maximum#591 at .\reducedim.jl:652 [inlined]
│  [11] maximum at .\reducedim.jl:652 [inlined]
│  [12] (::Main.BuildBlink.var"#1#4")() at C:\Users\appveyor\.julia\packages\Blink\AO8uN\src\AtomShell\install.jl:66
│  [13] cd(::Main.BuildBlink.var"#1#4", ::String) at .\file.jl:93
│  [14] install() at C:\Users\appveyor\.julia\packages\Blink\AO8uN\src\AtomShell\install.jl:27
│  [15] top-level scope at C:\Users\appveyor\.julia\packages\Blink\AO8uN\deps\build.jl:14
│  [16] include at .\boot.jl:328 [inlined]
│  [17] include_relative(::Module, ::String) at .\loading.jl:1105
│  [18] include(::Module, ::String) at .\Base.jl:31
│  [19] include(::String) at .\client.jl:424
│  [20] top-level scope at none:5
│ in expression starting at C:\Users\appveyor\.julia\packages\Blink\AO8uN\deps\build.jl:13
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
```

i.e.

https://github.com/JuliaGizmos/Blink.jl/blob/060c2023d07ad4ab7b367bc67791ae654f4a8e5e/src/AtomShell/install.jl#L66

which is Windows-specific code.

Note that the stack trace is different from #218, which appears to have been on OSX and which also appears to have been fixed.

**Comment by eisthf** [comment]
I face the same issue for Julia 1.3.0 on Windows 10:

(v1.3) pkg> build Blink                                                                                                                                                                         Building MbedTLS → `E:\.julia\packages\MbedTLS\a1JFn\deps\build.log`                                                                                                                          Building WebIO ──→ `E:\.julia\packages\WebIO\2nnB1\deps\build.log`                                                                                                                            Building Blink ──→ `E:\.julia\packages\Blink\AO8uN\deps\build.log`                                                                                                                          ┌ Error: Error building `Blink`:                                                                                                                                                              │ ERROR: LoadError: ArgumentError: reducing over an empty collection is not allowed                                                                                                           │ Stacktrace:                                                                                                                                                                                 │  [1] _empty_reduce_error() at .\reduce.jl:212                                                                                                                                               │  [2] reduce_empty(::Function, ::Type) at .\reduce.jl:222                                                                                                                                    │  [3] mapreduce_empty(::typeof(identity), ::Function, ::Type) at .\reduce.jl:247                                                                                                             │  [4] _mapreduce(::typeof(identity), ::typeof(max), ::IndexLinear, ::Array{VersionNumber,1}) at .\reduce.jl:301                                                                              │  [5] _mapreduce_dim at .\reducedim.jl:312 [inlined]                                                                                                                                         │  [6] #mapreduce#584 at .\reducedim.jl:307 [inlined]                                                                                                                                         │  [7] mapreduce at .\reducedim.jl:307 [inlined]                                                                                                                                              │  [8] _maximum at .\reducedim.jl:657 [inlined]                                                                                                                                               │  [9] _maximum at .\reducedim.jl:656 [inlined]                                                                                                                                               │  [10] #maximum#591 at .\reducedim.jl:652 [inlined]                                                                                                                                          │  [11] maximum at .\reducedim.jl:652 [inlined]                                                                                                                                               │  [12] (::Main.BuildBlink.var"#1#4")() at E:\.julia\packages\Blink\AO8uN\src\AtomShell\install.jl:66                                                                                         │  [13] cd(::Main.BuildBlink.var"#1#4", ::String) at .\file.jl:93                                                                                                                             │  [14] install() at E:\.julia\packages\Blink\AO8uN\src\AtomShell\install.jl:27                                                                                                               │  [15] top-level scope at E:\.julia\packages\Blink\AO8uN\deps\build.jl:14                                                                                                                    │  [16] include at .\boot.jl:328 [inlined]                                                                                                                                                    │  [17] include_relative(::Module, ::String) at .\loading.jl:1105                                                                                                                             │  [18] include(::Module, ::String) at .\Base.jl:31                                                                                                                                           │  [19] include(::String) at .\client.jl:424                                                                                                                                                  │  [20] top-level scope at none:5                                                                                                                                                             │ in expression starting at E:\.julia\packages\Blink\AO8uN\deps\build.jl:13                                                                                                                   └ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649

**Comment by tkoolen** [comment]
I seem to have confused myself, this was actually on 1.3 and is just a duplicate of #224.
