### ISSUE TITLE
Enable testing on Appveyor

### ISSUE THREAD

**Issue by tkoolen** [JuliaGizmos/Blink.jl#228]
The `appveyor.yml` as currently checked in seems to work fine (see [this build](https://ci.appveyor.com/project/tkoolen/blink-jl) on my fork of this repo), and would have caught #226. Would you mind enabling Appveyor builds for this repo (go to https://ci.appveyor.com, Projects > New Project > Blink.jl)?

**Comment by travigd** [comment]
I've done this. I'm not familiar at all with AppVeyor so please confirm if everything looks okay. :^) I didn't set anything in terms of settings (just used the defaults).

https://ci.appveyor.com/project/travigd/blink-jl

**Comment by tkoolen** [comment]
Awesome, thanks! I'm looking into #226 by the way.

**Comment by travigd** [comment]
Appreciate it! Don't have a Windows machine so not terribly useful here. :^)

More than happy to merge PR's that fix any issues.
