### ISSUE TITLE
Drop support for Julia 0.7

### ISSUE THREAD

**Issue by travigd** [JuliaGizmos/Blink.jl#233]
As title.

Few people are using Julia 0.7 in the wild and the Travis builds are sometimes flakey with Julia 0.7.

**Comment by travigd** [comment]
Apparently this was already done with the new Pkg registry (we didn't bound Julia so it was implicitly capped to v1+).

**Comment by NHDaly** [comment]
lol oops! 😅 Welllllll here's to the future? haha 🚀 🎸
