### ISSUE TITLE
[small] Button on README for stable docs gives 404

### ISSUE THREAD

**Issue by soumitradev** [JuliaGizmos/Blink.jl#244]
Title says it all

**Comment by NHDaly** [comment]
We've known about this for a while, i dunno why we never filed an issue for it.

When i created the Documentation pages, i couldn't figure out how to get it to generate the stable docs page, and no one has fixed this since then.
See: https://github.com/JuliaGizmos/Blink.jl/pull/168 and https://github.com/JuliaGizmos/Blink.jl/pull/173

Can anyone with more Documenter.jl experience help out here? Maybe @mortenpi? :)  Thanks!

**Comment by NHDaly** [comment]
Thanks for filing the issue, @soumitradev! :)

**Comment by mortenpi** [comment]
The `stable` gets populated when tags are being built, but you're not allowing Travis to run on tags:

https://github.com/JuliaGizmos/Blink.jl/blob/70215d6926a95c4795758c3a1da1d4c51eefc593/.travis.yml#L36-L38

You can set it to the following to get Travis builds on tags too:

```yaml
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
```

**Comment by NHDaly** [comment]
Thanks @mortenpi! I made the suggested fixed in f79de91.

I guess we'll need to tag a new release to get the change, since the change needs to be in the config at the tag...

Would it make sense to go back and cherry-pick this commit into the old releases, and make a patch release (or even like just add a `-docs` tag to the version or something?) in order to generate docs for them?

**Comment by NHDaly** [comment]
Hmm, i tried testing this by cherry-picking the commit and making a docs release as [v0.12.1-docs](https://github.com/JuliaGizmos/Blink.jl/releases/tag/v0.12.1-docs), and it _did_ get picked up by travis:
https://travis-ci.org/JuliaGizmos/Blink.jl/builds/650029903?utm_medium=notification&utm_source=github_status

But it looks like our `DOCUMENTER_KEY` wasn't configured correctly:
```
┌ Info: Deployment criteria for deploying release build from Travis:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="JuliaGizmos/Blink.jl" occurs in repo="github.com/JuliaGizmos/Blink.jl.git"
│ - ✔ ENV["TRAVIS_PULL_REQUEST"]="false" is "false"
│ - ✔ ENV["TRAVIS_TAG"] contains a valid VersionNumber
│ - ✘ ENV["DOCUMENTER_KEY"] exists
│ - ✔ ENV["TRAVIS_EVENT_TYPE"]="push" is not "cron"
└ Deploying: ✘
The command "xvfb-run julia --project=docs/ --color=yes docs/make.jl" exited with 0.
```
Which matches what we configured in Travis:
<img width="911" alt="Screen Shot 2020-02-13 at 1 43 09 PM" src="https://user-images.githubusercontent.com/1582097/74467293-ce1f2600-4e66-11ea-9de8-a048c3f0a3d4.png">

So we have to fix this as well.

here are the instructions to do that, but it needs to be someone with access to the settings on this repo. Might need to be you, @travigd?
https://github.com/JuliaGizmos/Blink.jl/pull/168#issuecomment-433214304

**Comment by NHDaly** [comment]
Unfortunately it looks like you can't edit the supported branches on the existing key, so we'll need to add a new key, and/or replace the existing key. For some reason, I have the privileges to add the secret key to Travis, but i can't set the public key on this Repo.

**Comment by travigd** [comment]
@NHDaly I added you as an admin on the repo. You should have been by default but things got overlooked when we transferred Blink to the JuliaGizmos org.

**Comment by NHDaly** [comment]
🙌 Hooray! It worked! :) Thanks Travis!

https://juliagizmos.github.io/Blink.jl/stable/
https://juliagizmos.github.io/Blink.jl/v0.12.2/

I'll tag a release for v0.12.2 now via Registrator.

**Comment by NHDaly** [comment]
🙌 Hooray! It worked! :) Thanks Travis!

https://juliagizmos.github.io/Blink.jl/stable/
https://juliagizmos.github.io/Blink.jl/v0.12.2/

I'll tag a release for v0.12.2 now via Registrator.

**Comment by NHDaly** [comment]
(ugh, despite the github issues right now)

--------

One thing that did _not_ work, is that I tried to go back and apply the changes to an older branch (by creating a new tag, `v0.11.1` from `v0.11.0`, which just cherry-picks the travis changes), but Documenter failed on that branch with this error:
https://travis-ci.org/JuliaGizmos/Blink.jl/jobs/654978874
```julia
ERROR: LoadError: MethodError: Cannot `convert` an object of type Symbol to an object of type Documenter.Writer
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154
Stacktrace:
 [1] setindex!(::Array{Documenter.Writer,1}, ::Symbol, ::Int64) at ./array.jl:769
 [2] getindex at ./array.jl:366 [inlined]
 [3] #Document#6(::String, ::String, ::String, ::Symbol, ::Symbol, ::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Symbol, ::Array{Regex,1}, ::Bool, ::Array{Module,1}, ::Array{Any,1}, ::Array{String,1}, ::String, ::String, ::String, ::String, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Type, ::Tuple{}) at /home/travis/.julia/packages/Documenter/HmOsT/src/Documents.jl:292
 [4] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:format, :modules, :sitename, :pages),Tuple{Symbol,Array{Module,1},String,Array{Any,1}}}, ::Type{Documenter.Documents.Document}, ::Tuple{}) at ./none:0
 [5] #makedocs#1(::Bool, ::Symbol, ::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:modules, :sitename, :pages),Tuple{Array{Module,1},String,Array{Any,1}}}}, ::Function) at /home/travis/.julia/packages/Documenter/HmOsT/src/Documenter.jl:235
 [6] (::getfield(Documenter, Symbol("#kw##makedocs")))(::NamedTuple{(:modules, :format, :sitename, :pages),Tuple{Array{Module,1},Symbol,String,Array{Any,1}}}, ::typeof(makedocs)) at ./none:0
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1044
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] exec_options(::Base.JLOptions) at ./client.jl:266
 [12] _start() at ./client.jl:425
in expression starting at /home/travis/build/JuliaGizmos/Blink.jl/docs/make.jl:5
```

@mortenpi: any ideas about that? Is it possible to go back and build docs for the old versions? :) Thanks!

**Comment by soumitradev** [comment]
Since this seems mostly figured out, I'll be closing this.
