### ISSUE TITLE
Error building Blink: can't find 7z.exe

### ISSUE THREAD

**Issue by Datseris** [JuliaGizmos/Blink.jl#247]
```
 Building Blink ───────→ `C:\Users\datse\.julia\packages\Blink\4FM8Y\deps\build.log`
┌ Error: Error building `Blink`:
│ ERROR: LoadError: Unable to find 7z.exe. Try running `make win-extras` if you built Julia from source.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] (::Main.BuildBlink.var"#1#2")() at C:\Users\datse\.julia\packages\Blink\4FM8Y\src\AtomShell\install.jl:55
│  [3] cd(::Main.BuildBlink.var"#1#2", ::String) at .\file.jl:93
│  [4] install() at C:\Users\datse\.julia\packages\Blink\4FM8Y\src\AtomShell\install.jl:27
│  [5] top-level scope at C:\Users\datse\.julia\packages\Blink\4FM8Y\deps\build.jl:14
│  [6] include at .\boot.jl:328 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1105
│  [8] include(::Module, ::String) at .\Base.jl:31
│  [9] include(::String) at .\client.jl:424
│  [10] top-level scope at none:5
│ in expression starting at C:\Users\datse\.julia\packages\Blink\4FM8Y\deps\build.jl:13
│ caused by [exception 1]
│ IOError: could not spawn `'C:\Users\datse\AppData\Local\Julia-1.3.1\bin\7z.exe' x electron-v4.0.4-win32-x64.zip -y -oatom`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
│  [2] setup_stdios(::Base.var"#554#555"{Cmd}, ::Array{Any,1}) at .\process.jl:112
│  [3] _spawn at .\process.jl:111 [inlined]
│  [4] #run#565(::Bool, ::typeof(run), ::Cmd) at .\process.jl:439
│  [5] run at .\process.jl:438 [inlined]
│  [6] (::Main.BuildBlink.var"#1#2")() at C:\Users\datse\.julia\packages\Blink\4FM8Y\src\AtomShell\install.jl:52
│  [7] cd(::Main.BuildBlink.var"#1#2", ::String) at .\file.jl:93
│  [8] install() at C:\Users\datse\.julia\packages\Blink\4FM8Y\src\AtomShell\install.jl:27
│  [9] top-level scope at C:\Users\datse\.julia\packages\Blink\4FM8Y\deps\build.jl:14
│  [10] include at .\boot.jl:328 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1105
│  [12] include(::Module, ::String) at .\Base.jl:31
│  [13] include(::String) at .\client.jl:424
│  [14] top-level scope at none:5
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
```
I have the 7zip file manager installed, but how do I solve this?

**Comment by travigd** [comment]
Did you build Julia from source?

**Comment by Datseris** [comment]
I downloaded a pre-compiled executable.

**Comment by travigd** [comment]
This is probably caused by #229, though that was supposed to fix these issues.

Can you report the output of `readdir(joinpath(Sys.BINDIR, Base.LIBEXECDIR))`?

For me (on a Mac):
```julia
julia> readdir(joinpath(Sys.BINDIR, Base.LIBEXECDIR))
1-element Array{String,1}:
 "7z"
```

**Comment by Datseris** [comment]
For me I get
```
julia> readdir(joinpath(Sys.BINDIR, Base.LIBEXECDIR))
2-element Array{String,1}:
 "7z.dll"
 "7z.exe"
```

**Comment by travigd** [comment]
Curious.  I'm not sure how to debug this any further.

The message
```
│ IOError: could not spawn `'C:\Users\datse\AppData\Local\Julia-1.3.1\bin\7z.exe' x electron-v4.0.4-win32-x64.zip -y -oatom`: no such file or directory (ENOENT)
```
is pretty informative: it failed to spawn `7z.exe`, which is weird since it looks like it exists.

What happens if you do this?
```julia
run(`C:\Users\datse\AppData\Local\Julia-1.3.1\bin\7z.exe`)
```

It should error (because we're not giving it the correct arguments), but it shouldn't be an `ENOENT` (which signifies that the executable doesn't actually exist).

**Comment by Datseris** [comment]
```
julia> run(`C:\Users\datse\AppData\Local\Julia-1.3.1\bin\7z.exe`)
ERROR: IOError: could not spawn `C:UsersdatseAppDataLocalJulia-1.3.1bin7z.exe`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99   
 [2] #554 at .\process.jl:112 [inlined]
 [3] setup_stdios(::Base.var"#554#555"{Cmd}, ::Array{Any,1}) at .\process.jl:196
 [4] _spawn at .\process.jl:111 [inlined]
 [5] #run#565(::Bool, ::typeof(run), ::Cmd) at .\process.jl:439
 [6] run(::Cmd) at .\process.jl:438
 [7] top-level scope at none:0
```

Hm, this is sad. It looks like its a problem on my end?

But I don't know how to solve it though.

**Comment by travigd** [comment]
Oh, sorry, I forgot to escape backslashes (see the `C:UsersdatseAppDataLocalJulia-1.3.1bin7z.exe` bit).

Try
```julia
run(`C:\\Users\\datse\\AppData\\Local\\Julia-1.3.1\\bin\\7z.exe`)
```

**Comment by Datseris** [comment]
I get
```
julia> run(`C:\\Users\\datse\\AppData\\Local\\Julia-1.3.1\\bin\\7z.exe`)
ERROR: IOError: could not spawn `'C:\Users\datse\AppData\Local\Julia-1.3.1\bin\7z.exe'`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
 [2] setup_stdios(::Base.var"#554#555"{Cmd}, ::Array{Any,1}) at .\process.jl:112       
 [3] _spawn at .\process.jl:111 [inlined]
 [4] #run#565(::Bool, ::typeof(run), ::Cmd) at .\process.jl:439
 [5] run(::Cmd) at .\process.jl:438
 [6] top-level scope at none:0
```

**Comment by travigd** [comment]
Oh, I think I see the issue. It should be `Julia-1.3.1\libexec\7z.exe`, but instead `libexec` is just `bin`.

Are you using the latest version of Blink (0.12.1)? That's where we made the change to use BinDeps instead of using the old logic (which I think had that bug, since the 7z exe was moved in Julia 1.3).

**Comment by Datseris** [comment]
Yes I am using latest stable version.

**Comment by travigd** [comment]
What's the output of

```julia
using Pkg
Pkg.add("BinDeps")
using BinDeps
@show BinDeps.unpack_cmd(file, "atom", ".zip", nothing)
```

**Comment by Datseris** [comment]
what's `file` in your code?

**Comment by travigd** [comment]
Whoops, I copied that out of the source. Any string should work.
```julia
@show BinDeps.unpack_cmd("foo", "atom", ".zip", nothing)
```

**Comment by Datseris** [comment]
```
julia> file = "7zip"
"7zip"

julia> @show BinDeps.unpack_cmd(file, "atom", ".zip", nothing)
BinDeps.unpack_cmd(file, "atom", ".zip", nothing) = `'C:\Users\datse\AppData\Local\Julia-1.3.1\bin\7z.exe' x 7zip -y -oatom`
`'C:\Users\datse\AppData\Local\Julia-1.3.1\bin\7z.exe' x 7zip -y -oatom`
```

**Comment by travigd** [comment]
This might be an issue with BinDeps then. Are you on the latest version of BinDeps?

BinDeps checks for the presence of `Base.LIBEXECDIR` (since that was added in Julia 1.3) and if it's defined uses that.
https://github.com/JuliaPackaging/BinDeps.jl/blob/master/src/BinDeps.jl#L11

**Comment by Datseris** [comment]
I just did 
```
using Pkg
Pkg.add("BinDeps")
```
so I guess I am on the latest version.....

Anyway, what is the workaround to build Blink then? Is there one?

**Comment by travigd** [comment]
```julia
julia> Pkg.status("BinDeps")
    Status `~/.julia/environments/v1.3/Project.toml`
  [9e28174c] BinDeps v1.0.0
```

Is yours the same? I think `Pkg.add(...)` doesn't necessarily update the package, it just adds it to your manifest so that you can `using ...`.

The hackiest hack that ever hacked would be

```julia
cp(joinpath(Sys.BINDIR, Base.LIBEXECDIR, "7z.exe"), joinpath(Sys.BINDIR, "7z.exe"))
```

but I'd definitely like to get to the bottom of this issue to make sure that it doesn't happen for anyone else.

**Comment by Datseris** [comment]
You were right
```
julia> Pkg.status("BinDeps")
    Status `C:\Users\datse\.julia\environments\v1.3\Project.toml`
  [9e28174c] BinDeps v0.8.10
```
damn, some other package is holding BinDeps back...

**Comment by Datseris** [comment]
Thank you for the support. This was a problem from my end. However, you should change the Project.toml compat entry to state version `1` for BinDeps and not something earlier.

**Comment by travigd** [comment]
#248

**Comment by YoshuaMoore** [comment]
Firstly, thank you travigd for your help here.
I recently made the switch from Julia v1.0.5 to v1.4.1 and Blink stopped working. Blink version was v0.12.1 for both Julia versions. 
I got exactly the same errors as Datseris described, and I could not use 'Blink.AtomShell.install()' as it was throwing the same errors as above. 
`ERROR: Cannot find Electron. Try `Blink.AtomShell.install()`.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] electron at C:\Users\Yoshua\.julia\packages\Blink\4FM8Y\src\AtomShell\process.jl:70 [inlined]
 [3] init(; debug::Bool) at C:\Users\Yoshua\.julia\packages\Blink\4FM8Y\src\AtomShell\process.jl:88
 [4] shell(; debug::Bool) at C:\Users\Yoshua\.julia\packages\Blink\4FM8Y\src\AtomShell\process.jl:129
 [5] shell() at C:\Users\Yoshua\.julia\packages\Blink\4FM8Y\src\AtomShell\process.jl:127
 [6] top-level scope at REPL[12]:1`

I had to manually install BinDeps v1.0.1 as you suggested and now everything is fine.
If I had not found your post here, I would have had some difficulty - Maybe there should be something put in the documentation that BinDeps v1.0.1 is required to avoid this? 
For the not-so-savvy like myself, this could have been a big headache.
Thanks

**Comment by rgrivel-cs** [comment]
This error has popped up again with Blink v0.12.5 and julia v1.9.0. Using a similar workaround as above I was able to resolve this issue by running the two lines of code:
`cp(joinpath(Sys.BINDIR, Base.LIBEXECDIR, "julia", "7z.exe"), joinpath(Sys.BINDIR, Base.LIBEXECDIR, "7z.exe"))`
`cp(joinpath(Sys.BINDIR, Base.LIBEXECDIR, "julia", "7z.dll"), joinpath(Sys.BINDIR, Base.LIBEXECDIR, "7z.dll"))`

**Comment by csufangyu** [comment]
hi, I use Blink v0.12.5 and  julia v1.9.0.I run the code 
`cp(joinpath(Sys.BINDIR, Base.LIBEXECDIR, "julia", "7z.exe"), joinpath(Sys.BINDIR, Base.LIBEXECDIR, "7z.exe"))
cp(joinpath(Sys.BINDIR, Base.LIBEXECDIR, "julia", "7z.dll"), joinpath(Sys.BINDIR, Base.LIBEXECDIR, "7z.dll"))`
but I get the new error:
`IOError: could not spawn `'E:\Julia-1.9.2\bin\..\libexec\7z.exe' x electron-v4.0.4-win32-x64.zip -y -oatom`: no such file or directory (ENOENT)`

**Comment by pfitzseb** [comment]
Please use newer versions of Blink to fix that error.

**Comment by Realyyc** [comment]
it is really easy to solve it! just copy the file in `D:\julia\julia-1.9.3\Julia-1.9.3\libexec\julia` to `D:\julia\julia-1.9.3\Julia-1.9.3\libexec`

**Comment by digital-carver** [comment]
This happened to me just now on Windows (preventing me from installing Plotly since Blink is an indirect dependency of it). 

I can try the file copy workaround, but is there a reason such an old and known issue still requires a manual hack from the users rather than a code fix? It seems like the location changed to be under `libexec/julia/` with https://github.com/JuliaLang/julia/pull/48931 , so Blink.jl using that location by default for Julia 1.9 and above will save a lot of people the trouble and time spent in figuring this out.
