### ISSUE TITLE
on Julia 1.6-dev: UndefVarError: window_defaults not defined

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaGizmos/Blink.jl#272]
on Win 10. To replicate: 
```
using Blink
w = Window()
```

**Comment by jacobadenbaum** [comment]
I can confirm that I have the same problem on both Mac and Linux machines, so this doesn't appear to be windows specific.

**Comment by pkofod** [comment]
I have the same issue on beta. I'm not sure what the issue is, but it's coming from here https://github.com/JuliaGizmos/Blink.jl/blob/3480c39dcbc40fc6865ce09fcef64f9a89ce1e98/src/AtomShell/window.jl#L35 . Maybe some changes to how macros behave? Either an unintended brekaing change in julia or some bad metaproramming in `@js` that doesn't "follow the rules" :)

**Comment by andreasnoack** [comment]
@KristofferC Do you have any idea what could have caused this?

**Comment by KristofferC** [comment]
The difference is:

```julia
julia> @macroexpand @js a createWindow($(merge(window_defaults, opts)))
# 1.6:
:(Blink.js(a, Core._expr(:call, :createWindow, Blink.merge(Blink.window_defaults, Blink.opts))))
# 1.5:
:(Blink.js(a, Core._expr(:call, :createWindow, merge(window_defaults, opts))))
```

This was changed (bug fixed) in https://github.com/JuliaLang/julia/pull/37573 to require escaping.

The fix should be something like:

````diff
diff --git a/src/rpc/rpc.jl b/src/rpc/rpc.jl
index 2698439..1057bef 100644
src/rpc/rpc.jl
@@ -79,7 +79,7 @@ julia> @js_ win for i in 1:x console.log(i) end
 ```
 """
 macro js(o, ex)
-    :(js($(esc(o)), $(Expr(:quote, ex))))
+    :(js($(esc(o)), $(esc(Expr(:quote, ex)))))
 end

 """
@@ -102,5 +102,5 @@ julia> @js_ win for i in 1:x console.log(i) end
 ```
 """
 macro js_(o, ex)
-    :(js($(esc(o)), $(Expr(:quote, ex)), callback=false))
+    :(js($(esc(o)), $(esc(Expr(:quote, ex))), callback=false))
 end
~
````

**Comment by andreasnoack** [comment]
Thanks. While trying to fix this I hit a similar issue with https://github.com/JuliaGizmos/Blink.jl/blob/3480c39dcbc40fc6865ce09fcef64f9a89ce1e98/src/AtomShell/window.jl#L195-L196 but even though I tried to add `esc` at various places in https://github.com/JuliaGizmos/Blink.jl/blob/3480c39dcbc40fc6865ce09fcef64f9a89ce1e98/src/AtomShell/window.jl#L100-L106 but `w` and `h` keep being qualified
```julia
julia> Base.uncompressed_ast(collect(methods(size, Tuple{Blink.Window, Any, Any}))[2])
CodeInfo(
    @ /Users/andreasnoack/.julia/dev/Blink/src/AtomShell/window.jl:195 within `size'
1 ─ %1 = Core._expr(:call, :setSize, Blink.AtomShell.w, Blink.AtomShell.h)
│   %2 = Core._expr(:escape, %1)
│   %3 = Core.QuoteNode(%2)
│   %4 = Core._expr(:., :this, %3)
│   %5 = Blink.AtomShell.dot_(win, %4)
└──      return %5
```
Any idea how to fix this one?

**Comment by PaulSoderlind** [comment]
Version 0.12.4 seems to fix this. Thanks
