### ISSUE TITLE
Blink Suitable for Complex React UI? 

### ISSUE THREAD

**Issue by markhalonen** [JuliaGizmos/Blink.jl#276]
I am thinking of using Blink for a desktop app with a large ui.

With a large ui, I find React/Typescript to be essential for managing complexity. 

It seems Electron comes pre-baked in this Blink paradigm. I think I would want full control of my Electron app to manage updates, installers, etc.

Would it be possible to install Blink to an electron app as an `npm` module?

is Blink designed for large user interfaces implemented using the full JavaScript toolset? 

I am thinking my other alternative is to use something like Redis as the communication channel between JavaScript UI and the Julia backend

**Comment by pfitzseb** [comment]
I wouldn't recommend using Blink for much more than some quick prototyping, tbh. 
Building a standalone API and communicating over sockets, a REST API, or indeed Redis seems like a much more robust approach.
