### ISSUE TITLE
Manifest requests old versions of packages

### ISSUE THREAD

**Issue by lewisl** [JuliaGizmos/Blink.jl#294]
This interferes with updating to latest versions of other packages like Plots.

Perhaps this package is now "fallow" (polite for dead or unmaintained).

It's ok. I used it and liked it, but can't use it any more.

Not asking for anything here.  It's a choice to gradually let usage of the package decline.

**Comment by pdeffebach** [comment]
@lewisl This is a generally unhelpful issue. Can you let us know the specific packages that are causing problems?

**Comment by lewisl** [comment]
Sorry.  I just deleted the offending packages and moved on.

It seems like issues around hard preferences for old versions of packages has gotten a lot worse over the past 9 months. Before that I never saw it.

Perhaps the guideline for hardcoded dependency versions should be to use a > constraint?  It seems the only reason to use an equality constraint for an old version of a dependency is you are a package developer testing something; your package is closer to what Karpinsky refers to as an “application” and you just need to get it working.  For any package meant to be broadly used you’d think the requirement should be greater than.

As a matter of “culture” among package developers just working with the latest is beneficial to the largest number of users who simply install from the central package index without ever specifying a version.

I may be unusual among Julia users, but I don’t want to ever repeat the Python mess of having lots of individual “env’s” with specific requirements. I just have a global env and forget about it.

From: pdeffebach ***@***.***>
Reply-To: "JuliaGizmos/Blink.jl" ***@***.***>
Date: Monday, November 14, 2022 at 8:00 AM
To: "JuliaGizmos/Blink.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Mention ***@***.***>
Subject: Re: [JuliaGizmos/Blink.jl] Manifest requests old versions of packages (Issue #294)


@lewisl<https://github.com/lewisl> This is a generally unhelpful issue. Can you let us know the specific packages that are causing problems?

**Comment by BoundaryValueProblems** [comment]
I have exactly the same problem as @PaulSoderlind mentioned when I try to update the packages, in particular, HTTP v.1.5.5. I hope this will be resolved soon!

**Comment by anj00** [comment]
I did PR which makes sure that one can move to latest Mux, it needed some code changes. Maybe someone with the write access can take a look and make it a release?

But don't get your hopes too high. Currently Blink is using very old version of WebIO. and it may be blocking some other packages. So WebIO needs to be updated as well to the latest HTTP etc. But looks like atm Blink is blocking WebIO update (yeah, some circular dependency going on there. So might take some iterations to get right )

https://github.com/JuliaGizmos/Blink.jl/pull/295
