### ISSUE TITLE
Remove dependency on Lazy.jl

### ISSUE THREAD

**Issue by pdeffebach** [JuliaGizmos/Blink.jl#323]
Lazy.jl commits some type piracy. See [this](https://discourse.julialang.org/t/how-to-detect-avoid-type-piracy/114588/6) discourse thread. It also doesn't appear to be maintained. Also see source code [here](https://github.com/MikeInnes/Lazy.jl/blob/6705a0aa95b2d479e4ca5b5593313b0d6a857966/src/collections.jl#L3). 

I don't know the extent of how Blink.jl uses Lazy.jl, though. But it seems worth flagging.

**Comment by simsurace** [comment]
Its only `Lazy.@init` and `Lazy.@errs`, I opened a PR to remove it and replaced these two macros.
