### ISSUE TITLE
Make loadurl synchronous

### ISSUE THREAD

**Issue by EricForgy** [JuliaGizmos/Blink.jl#41]
I think programming with Blink is better if everything is synchronous by default.

With #35, I made opening a Window synchronous. Next, I want to make loading a URL synchronous/blocking.

Any thoughts?

**Comment by shashi** [comment]
I tend to agree with this. Synchronous by default seems to be the Julia style. If you want something to be asynchronous you can always call it with `@async`. I just made a PR #56 to make `importhtml!` synchronous

**Comment by travigd** [comment]
Closing as stale. Feel free to open a new issue if you want to talk about this.
