### ISSUE TITLE
How can I add a feature to increase text size

### ISSUE THREAD

**Issue by yeison** [JuliaGizmos/Blink.jl#46]
I'd like to be able to increase the text size in the electron window using a standard shortcut like shift-cmd-+

Where should I begin.

**Comment by one-more-minute** [comment]
Just increasing text size, or zooming in the whole page as a browser would? For the latter, there's some mentions of zooming on the [electron window docs](https://github.com/atom/electron/blob/master/docs/api/browser-window.md) – if you can find the appropriate API function you can call it from Blink.jl.

**Comment by rafaqz** [comment]
In case anyone comes searching for this again:
w = Window(Dict("webPreferences"=>Dict("zoomFactor"=>0.7)))
