### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by BenJWard** [JuliaGizmos/Blink.jl#57]
Hi, I really like the looks of Blink.jl and am intrigues about the possibility of creating simple but attractive apps for bioinformatics that are powered by Julia, and BioJulia, and thanks to Blink, HTML and CSS, look great! However, I am unable to get up and running with it, pretty pretty please can we have some documentation, the types and methods available, and maybe a simple tutorial on how to make a simple app?

**Comment by MikeInnes** [comment]
More docs and tutorials would be wonderful, but unfortunately it also takes a lot of time and I think the developers of this package are pretty busy right now.

What might work well is for you to ask whatever specific questions you have, and if someone knows the answer they can help out. That way you can start to get to grips with things, and it'll be a great way to have a hand in shaping the package to your needs as well (I think Blink could be great for your use case, but we've mainly used it for plotting and stuff so far). If you can publish some small notes on your experience getting to grips with the package, all the better!

**Comment by Ward9250** [comment]
So if I start with something simple, using blink is it possible to have a slider input, say 1 to ten, and a button to click "go" and when go it clicked, the value from the slider is used in a simple function?

**Comment by Ward9250** [comment]
Ok I have a first simple example and a question.

Suppose I create this incredibly simple UI:

```julia
using Blink

body!(w, "My Fancy App!<br/><br/><button id='gobutton'>Click me!</button>")
```

How can I detect when a button is pressed, and then on button press, execute some julia function?

**Comment by MikeInnes** [comment]
Ok so the way you'd do this at the moment is via message passing (I had planned to implement a more convenient callback-based interface but never got around to it).

Here's roughly what that looks like:

```julia
handle(w, "press") do args...
  @show args
end
@js_ w document.querySelector("gobutton").onclick = () -> Blink.msg("press", "foo")
```

If you get this working and press the button it should pass the tuple `("foo",)` to Julia and print it.

This works in reverse as well, so you can do `Blink.handle(type, f)` on the JS side and `msg(w, type, args...)` on the julia side.

**Comment by Ward9250** [comment]
Cool thanks I'll give this a try. I have simple app in mind with a text box for me to type in a file, a button to hit go, some stuff will happen and then it will display a plot in the window or a new window.

As an additional question, do you know why when I first open julia and Blink and try to do window() it shows this error (I'm on OSX), but then when I do it again the window appears fine.

```julia
julia> w = Window()
ERROR: connect: connection refused (ECONNREFUSED)
 in yieldto at ./task.jl:71
 in wait at ./task.jl:371
 in wait at ./task.jl:286
 in stream_wait at ./stream.jl:60
 in wait_connected at ./stream.jl:336
 in connect at socket.jl:671
 in try_connect at /Users/axolotlfan9250/.julia/v0.4/Blink/src/AtomShell/process.jl:62
 in init at /Users/axolotlfan9250/.julia/v0.4/Blink/src/AtomShell/process.jl:76
 in shell at /Users/axolotlfan9250/.julia/v0.4/Blink/src/AtomShell/process.jl:114
 in call at /Users/axolotlfan9250/.julia/v0.4/Blink/src/AtomShell/window.jl:37
```

**Comment by Ward9250** [comment]
So I've tried this example below, where I want to click the button and have julia print hello world. But when I click the button I don't seem to get a reaction.

```julia
julia> using Blink

julia> w = Window()
Blink.AtomShell.Window(1,Blink.AtomShell.Electron(Process(`/Users/axolotlfan9250/.julia/v0.4/Blink/deps/Julia.app/Contents/MacOS/Electron /Users/axolotlfan9250/.julia/v0.4/Blink/src/AtomShell/main.js port 8812`, ProcessRunning),TCPSocket(active, 0 bytes waiting),Dict{ByteString,Any}("callback"=>(anonymous function))),Blink.Page(1,WebSockets.WebSocket(5,TCPSocket(active, 0 bytes waiting),false,false),Dict{ByteString,Any}("callback"=>(anonymous function)),Condition(Any[])))

julia> body!(w, "My Fancy App!<br/><br/><button id='gobutton'>Click me!</button>")
Blink.Page(1,WebSockets.WebSocket(5,TCPSocket(active, 0 bytes waiting),false,false),Dict{ByteString,Any}("callback"=>(anonymous function)),Condition(Any[]))

julia> handle(w, "press") do args...
         println("Hello world!")
       end
(anonymous function)

julia> @js_ w document.querySelector("gobutton").onclick = () -> Blink.msg("press", "foo")

Blink.Page(1,WebSockets.WebSocket(5,TCPSocket(active, 0 bytes waiting),false,false),Dict{ByteString,Any}("press"=>(anonymous function),"callback"=>(anonymous function)),Condition(Any[]))

julia> 
```

**Comment by Ward9250** [comment]
I had wondered if it was the line `@js_ w document.querySelector("gobutton").onclick = () -> Blink.msg("press", "foo")` that was wrong and that the proper line was perhaps `@js_ w document.querySelector("gobutton").onclick = function(){Blink.msg("press", "foo");};`, But no such luck.

**Comment by Ward9250** [comment]
@MikeInnes I realised my dumb mistake and changed my `@js_` line to use `document.getElementById` instead of `document.querySelector`, and now clicking the button does do something, but there seems to be a method error:

```julia
julia> MethodError: `getindex` has no method matching getindex(::UTF8String, ::ASCIIString)
Closest candidates are:
  getindex(::UTF8String, ::UnitRange{Int64})
  getindex(::AbstractString, ::UnitRange{Int64})
  getindex(::AbstractString, ::Int64)
  ...
 [inlined code] from /Users/axolotlfan9250/.julia/v0.4/Lazy/src/macros.jl:259
 in ws_handler at /Users/axolotlfan9250/.julia/v0.4/Blink/src/content/server.jl:53
 in splitquery at /Users/axolotlfan9250/.julia/v0.4/Mux/src/basics.jl:28
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in wcatch at /Users/axolotlfan9250/.julia/v0.4/Mux/src/websockets_integration.jl:12
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in todict at /Users/axolotlfan9250/.julia/v0.4/Mux/src/basics.jl:21
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:12 (repeats 2 times)
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/server.jl:38
 in handle at /Users/axolotlfan9250/.julia/v0.4/WebSockets/src/WebSockets.jl:382
 in on_message_complete at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/HttpServer.jl:419
 in on_message_complete at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/RequestParser.jl:104
 in http_parser_execute at /Users/axolotlfan9250/.julia/v0.4/HttpParser/src/HttpParser.jl:92
 in process_client at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/HttpServer.jl:388
 in anonymous at task.jl:447
```

I'm not sure of the cause, I wondered if it was because of the passing of string foo from js to julia???

**Comment by Ward9250** [comment]
Hmm actually changing the handler to:

```julia
handle(w, "press") do args...
    return 5 + 9
end
```

and the js line to `@js_ w document.getElementById("gobutton").onclick = () -> Blink.msg("press", 0)`

still results in a method error:

```julia
MethodError: `getindex` has no method matching getindex(::Int64, ::ASCIIString)
Closest candidates are:
  getindex(::Number)
  getindex(::Number, ::Integer)
  getindex(::Number, ::Integer...)
  ...
 [inlined code] from /Users/axolotlfan9250/.julia/v0.4/Lazy/src/macros.jl:259
 in ws_handler at /Users/axolotlfan9250/.julia/v0.4/Blink/src/content/server.jl:53
 in splitquery at /Users/axolotlfan9250/.julia/v0.4/Mux/src/basics.jl:28
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in wcatch at /Users/axolotlfan9250/.julia/v0.4/Mux/src/websockets_integration.jl:12
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in todict at /Users/axolotlfan9250/.julia/v0.4/Mux/src/basics.jl:21
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:12 (repeats 2 times)
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/server.jl:38
 in handle at /Users/axolotlfan9250/.julia/v0.4/WebSockets/src/WebSockets.jl:382
 in on_message_complete at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/HttpServer.jl:419
 in on_message_complete at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/RequestParser.jl:104
 in http_parser_execute at /Users/axolotlfan9250/.julia/v0.4/HttpParser/src/HttpParser.jl:92
 in process_client at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/HttpServer.jl:388
 in anonymous at task.jl:447
```

**Comment by tomerarnon** [comment]
I see that this is an old issue, @Ward9250 , but did you ever get anywhere with this? I'm also looking to get started with Blink (or at least see if it's the right thing for me) and thorough documentation is still lacking.
