### ISSUE TITLE
A minor development(?) request

### ISSUE THREAD

**Issue by semmottos** [JuliaGizmos/Blink.jl#7]
Hi!

Firstly: thanks, thanks a lot. Blink works beautifully in what I'm using it for.

Secondly: I coded my first Fortran programs in 1970, have used about 40 programming languages but my trip with Julia started just 6 weeks ago and I know almost nothing of Git/Github so maybe more than a grain of salt is in need.

The app is a word translation quiz. It has two windows, one Blink window covering almost all of the screen area and at the bottom a tiny Gtk window, almost a slice only, that has the control over the execution. The program shows a word in the Blink window (at the same time pronouncing it thrice with the shell command 'say -v Daniel  word, word, word'), lets the user introspect if he (= me) knows the word and if he does, what kind of translations from English to Finnish he knows for that word.

The user interacts with the Gtk window and when he gives some of the allowed letters to signal his knowledge level the word in the Blink window is replaced with the Google Translate translation url of the word.

After the user has re-estimated his knowledge  level of the word  by going through the different translation meanings he gives a letter and a new word is shown.

When the user wants to stop, the program closes the Gtk window but I think there is no method to close the Blink window. I can of course close it manually but it would be convenient if there was a close/destroy method for that.

I decided to give GitHub a try and if I could do it myself I maybe might make a pull request. So I made a fork and copied  the front method in window.jl and tried to make a destroy method of it and export it also. That may or may not be the way to do it, I don't know. And then I tried to clone Blink from my fork.

Everything seems to be OK, I can import Blink but when I call Blink.init() I get an error message. Here' s what happens after I have removed the Blink line from REQUIRE and start the julia REPL:

julia> Pkg.resolve()
INFO: Removing Blink v0.1.4

julia> import Blink
ERROR: Blink not found
 in require at loading.jl:47

julia> using Blink
ERROR: Blink not found
 in require at loading.jl:47

julia> Pkg.clone("git://github.com/semmottos/Blink.jl","Blink")
INFO: Cloning Blink from git://github.com/semmottos/Blink.jl
INFO: Computing changes...
INFO: Installing Mustache v0.0.11
INFO: Package database updated

julia> atomshellinst = Blink.init() # initialise the atom-shell process
ERROR: Blink not defined

julia> import Blink

julia> atomshellinst = Blink.init() # initialise the atom-shell process
ERROR: `init` has no method matching init()

julia> methods(init)
ERROR: init not defined

julia> methods(Blink)
ERROR: `methods` has no method matching methods(::Module)

julia> methods(Blink.init)
#1 method for generic function "init":

init(xs) at /Users/IsoPomo/.julia/v0.3/Lazy/src/collections.jl:32

julia> Pkg.resolve()
INFO: No packages to install, update or remove

Having reached a deadlock, here's the request: could you add the close/destroy method(s) to a future release?

**Comment by one-more-minute** [comment]
Awesome to hear that this is proving useful for someone :)

The reason you're hitting on problems is that Blink has undergone quite a few changes recently, and I've changed the way it works a little (including removing the Blink.init() function). When you check out the latest version you're seeing those changes, but understandably are a bit lost since the new API isn't documented yet.

I'll try to get the update tagged and released and update the readme soon, which should make it much easier to play around with development.
