### ISSUE TITLE
loadjs! should support defer property

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaGizmos/Blink.jl#70]
maybe `deferjs!(w, url)` or `loadjs!(w, url, defer::Bool=false)`

if defered, it has to be handled slightly differently otherwise it will hang when executed

the use case is Material Design Lite, which wants this included

``` html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>
```

**Comment by shashi** [comment]
I would try `t = @async loadjs!(w, url)`

If you want to run something after the js file has been loaded, you can do `wait(t); @js w ...`
